version: "3.7"
services:
  prometheus:
    image: prom/prometheus:latest
    ports: 
      - 9090:9090
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/prometheus/alerting.rules:/etc/prometheus/alerting.rules
      - ./data-prometheus:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--storage.tsdb.retention.time=30d"
    depends_on:
      - cloudwatchexporter_oregon
      - cloudwatchexporter_virginia
      - sqs-exporter
      - cadvisor
      - alertmanager
    links:
      - cloudwatchexporter_oregon
      - cloudwatchexporter_virginia
      - sqs-exporter
      - cadvisor
      - alertmanager
    env_file:
      - ./aws_credentials

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./data-grafana:/var/lib/grafana
    depends_on:
      - prometheus
    links:
      - prometheus

  cloudwatchexporter_oregon:
    image: prom/cloudwatch-exporter 
    ports: 
      - "9106:9106"
    env_file:
      - ./aws_credentials
    volumes:
      - ./config/cloudwatch/cloudwatchexporter_oregon.yaml:/config/config.yml

  cloudwatchexporter_virginia:
    image: prom/cloudwatch-exporter 
    ports: 
      - "9107:9106"
    env_file:
      - ./aws_credentials
    volumes:
      - ./config/cloudwatch/cloudwatchexporter_virginia.yaml:/config/config.yml

  sqs-exporter:
    image: jmal98/sqs-exporter:latest
    ports:
      - 9384:9384
    env_file:
      - ./aws_credentials

  cadvisor:
    image: google/cadvisor:latest
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./config/alertmanager/alertmanager_conf.yaml:/etc/alertmanager/alertmanager.yml

