version: "3.7"
services:
  prometheus:
    image: prom/prometheus:latest
    ports: 
      - 9090:9090
    volumes:
      - /home/augusto/tmp/prometheus-docker/prometheus.yml:/etc/prometheus/prometheus.yml
      - /home/augusto/tmp/prometheus-docker/alerting.rules:/etc/prometheus/alerting.rules
    depends_on:
    - cloudwatchexporter
    - cadvisor
    - alertmanager
    links:
    - cloudwatchexporter
    - cadvisor
    - alertmanager

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
    - /home/augusto/tmp/prometheus-docker/data-grafana:/var/lib/grafana
    depends_on:
    - prometheus
    links:
    - prometheus

  cloudwatchexporter:
    image: prom/cloudwatch-exporter 
    ports: 
    - "9106:9106"
    environment:
    - AWS_ACCESS_KEY_ID=
    - AWS_SECRET_ACCESS_KEY=
    volumes:
    - /home/augusto/tmp/prometheus-docker/cloudwatchexporter.yaml:/config/config.yml

  cadvisor:
    image: google/cadvisor:latest
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:ro
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    - /dev/disk/:/dev/disk:ro

  alertmanager:
    image: prom/alertmanager
    ports:
    - 9093:9093
    volumes:
    - /home/augusto/tmp/prometheus-docker/alertmanager_conf.yaml:/etc/alertmanager/alertmanager.yml
